name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nicknovitski/nix-develop@v1
    - run: make
    - run: cargo test
    - run: cargo miri test -p rts
    - run: |
        set +e
        cargo run -- -e
        if [ $? = 6 ]; then
          exit 0
        else
          exit 1
        fi
    - run: |
        cargo run
        cc main.o -o main
        set +e
        valgrind ./main
        if [ $? = 6 ]; then
          exit 0
        else
          exit 1
        fi
