name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: nix flake check
    - run: nix develop -c make
    - run: nix develop -c cargo build
    - run: nix develop -c cargo test
    - run: nix develop -c cargo miri test -p rts
    - run: nix develop -c cargo run -- -e ; [ $? = 6 ]
    - run: nix develop -c cargo run && cc main.o -o main && valgrind ./main ; [ $? = 6 ]
